<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
		<PackageId>LogicBuilder.App.Spa.AutoMapperProfiles</PackageId>
		<Authors>BlaiseD</Authors>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>true</WarningsAsErrors>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<Description>This library serves as a shared location for mapping profiles which map the parameters encapsulating the form features defined in the logic builder to the serializable descriptors used to implement those features in a single page application (SPA) at runtime.</Description>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageReleaseNotes>First release.</PackageReleaseNotes>
		<PackageTags>form configuration</PackageTags>
		<Copyright>Copyright © BPS 2026</Copyright>
		<RepositoryUrl>https://github.com/BpsLogicBuilder/LogicBuilder.App.Spa.AutoMapperProfiles</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/BpsLogicBuilder/LogicBuilder</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
		<AssemblyOriginatorKeyFile>..\LogicBuilder.Rules.snk</AssemblyOriginatorKeyFile>
		<SignAssembly>true</SignAssembly>
		<MinVerTagPrefix>v</MinVerTagPrefix>
		<DebugType>embedded</DebugType>
		<Deterministic>true</Deterministic>
		<EmbedAllSources>true</EmbedAllSources>
		<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\icon.png" Pack="true" PackagePath="\" Visible="False" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="LogicBuilder.App.Spa.Forms.Configuration" Version="1.0.1" />
    <PackageReference Include="LogicBuilder.App.Spa.Forms.Parameters" Version="1.0.1" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" PrivateAssets="All" />
		<PackageReference Include="MinVer" Version="7.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
  </ItemGroup>

</Project>
